import { TrackingDelivery } from '../models/tracking-model';

// Mock data completa
export const mockDeliveries: TrackingDelivery[] = [
    {
      id: 'DEL-001', packageId: 'PKG-001',
      senderName: 'Juan Pérez', recipientName: 'María García',
      origin: 'Lima', destination: 'Arequipa',
      status: 'delivered',
      driver: 'Carlos López', driverPhone: '+51 999 111 222', truck: 'ABC-123',
      createdAt: '2026-02-10', estimatedDate: '2026-02-13',
      weight: 2.5, category: 'Electrónico', width: 30, height: 20, length: 15,
      currentLocation: 'Arequipa', eta: 'Entregado',
      timeline: [
        { status: 'registered', label: 'Registrado',       description: 'Paquete registrado en el sistema',      date: '10 Feb, 08:00', done: true,  active: false },
        { status: 'picked_up',  label: 'Recogido',         description: 'Paquete recogido por el conductor',     date: '10 Feb, 10:30', done: true,  active: false },
        { status: 'in_transit', label: 'En tránsito',      description: 'En camino hacia Arequipa',             date: '10 Feb, 11:00', done: true,  active: false },
        { status: 'arrived',    label: 'Llegó a destino',  description: 'El paquete llegó a Arequipa',          date: '13 Feb, 09:15', done: true,  active: false },
        { status: 'delivered',  label: 'Entregado',        description: 'Entregado a María García',             date: '13 Feb, 10:00', done: true,  active: true  },
      ],
    },
    {
      id: 'DEL-002', packageId: 'PKG-002',
      senderName: 'Empresa SAC', recipientName: 'Pedro Ruiz',
      origin: 'Lima', destination: 'Cusco',
      status: 'in_transit',
      driver: 'Ana Torres', driverPhone: '+51 999 333 444', truck: 'XYZ-456',
      createdAt: '2026-02-15', estimatedDate: '2026-02-19',
      weight: 5.0, category: 'Ropa', width: 45, height: 35, length: 25,
      currentLocation: 'Abancay', eta: 'Hoy, 18:00',
      timeline: [
        { status: 'registered', label: 'Registrado',       description: 'Paquete registrado en el sistema',     date: '15 Feb, 09:00', done: true,  active: false },
        { status: 'picked_up',  label: 'Recogido',         description: 'Paquete recogido por Ana Torres',      date: '15 Feb, 11:00', done: true,  active: false },
        { status: 'in_transit', label: 'En tránsito',      description: 'En camino — actualmente en Abancay',  date: '16 Feb, 08:30', done: true,  active: true  },
        { status: 'arrived',    label: 'Llegó a destino',  description: 'Pendiente',                           date: '—',             done: false, active: false },
        { status: 'delivered',  label: 'Entregado',        description: 'Pendiente',                           date: '—',             done: false, active: false },
      ],
    },
    {
      id: 'DEL-003', packageId: 'PKG-003',
      senderName: 'Lucía Mendoza', recipientName: 'Tech Corp',
      origin: 'Trujillo', destination: 'Lima',
      status: 'pending',
      driver: 'Sin asignar', driverPhone: '—', truck: 'Sin asignar',
      createdAt: '2026-02-18', estimatedDate: '2026-02-21',
      weight: 1.2, category: 'Documento', width: 20, height: 10, length: 10,
      currentLocation: 'Trujillo (origen)', eta: '21 Feb, ~12:00',
      timeline: [
        { status: 'registered', label: 'Registrado',       description: 'Paquete registrado en el sistema',     date: '18 Feb, 14:00', done: true,  active: true  },
        { status: 'picked_up',  label: 'Recogido',         description: 'Pendiente de asignación',             date: '—',             done: false, active: false },
        { status: 'in_transit', label: 'En tránsito',      description: 'Pendiente',                           date: '—',             done: false, active: false },
        { status: 'arrived',    label: 'Llegó a destino',  description: 'Pendiente',                           date: '—',             done: false, active: false },
        { status: 'delivered',  label: 'Entregado',        description: 'Pendiente',                           date: '—',             done: false, active: false },
      ],
    },
    {
      id: 'DEL-004', packageId: 'PKG-004',
      senderName: 'Distribuidora Norte', recipientName: 'José Flores',
      origin: 'Piura', destination: 'Lima',
      status: 'failed',
      driver: 'Miguel Sánchez', driverPhone: '+51 999 555 666', truck: 'LMN-789',
      createdAt: '2026-02-12', estimatedDate: '2026-02-15',
      weight: 8.3, category: 'Alimento', width: 60, height: 40, length: 30,
      currentLocation: 'Lima (intento fallido)', eta: 'Entrega fallida',
      timeline: [
        { status: 'registered', label: 'Registrado',       description: 'Paquete registrado en el sistema',     date: '12 Feb, 08:00', done: true,  active: false },
        { status: 'picked_up',  label: 'Recogido',         description: 'Recogido por Miguel Sánchez',          date: '12 Feb, 10:00', done: true,  active: false },
        { status: 'in_transit', label: 'En tránsito',      description: 'En camino hacia Lima',                date: '12 Feb, 11:30', done: true,  active: false },
        { status: 'arrived',    label: 'Llegó a destino',  description: 'Llegó a Lima',                        date: '15 Feb, 07:00', done: true,  active: false },
        { status: 'failed',     label: 'Entrega fallida',  description: 'Destinatario no encontrado',          date: '15 Feb, 09:30', done: true,  active: true  },
      ],
    },
    {
      id: 'DEL-005', packageId: 'PKG-005',
      senderName: 'Rosa Chávez', recipientName: 'Import SA',
      origin: 'Lima', destination: 'Iquitos',
      status: 'in_transit',
      driver: 'Carlos López', driverPhone: '+51 999 111 222', truck: 'ABC-123',
      createdAt: '2026-02-17', estimatedDate: '2026-02-22',
      weight: 3.7, category: 'Otro', width: 25, height: 25, length: 20,
      currentLocation: 'Pucallpa', eta: 'Mañana, ~10:00',
      timeline: [
        { status: 'registered', label: 'Registrado',       description: 'Paquete registrado en el sistema',     date: '17 Feb, 10:00', done: true,  active: false },
        { status: 'picked_up',  label: 'Recogido',         description: 'Recogido por Carlos López',            date: '17 Feb, 13:00', done: true,  active: false },
        { status: 'in_transit', label: 'En tránsito',      description: 'En camino — actualmente en Pucallpa', date: '18 Feb, 09:00', done: true,  active: true  },
        { status: 'arrived',    label: 'Llegó a destino',  description: 'Pendiente',                           date: '—',             done: false, active: false },
        { status: 'delivered',  label: 'Entregado',        description: 'Pendiente',                           date: '—',             done: false, active: false },
      ],
    },
];